import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:fluttersipay/utils/custom_text_style.dart';
import 'package:localize_and_translate/localize_and_translate.dart';
import 'package:fluttersipay/dashboard/drawerMenu.dart';

TextEditingController _phoneController = TextEditingController();

class LoginRegisterScreen extends StatefulWidget {
  LoginRegisterScreen({Key key}) : super(key: key);

  @override
  LoginRegisterScreenState createState() => LoginRegisterScreenState();
}

class LoginRegisterScreenState extends State<LoginRegisterScreen> {
  bool _checkPhone = true;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);
    ScreenUtil.instance = ScreenUtil.getInstance()..init(context);
    ScreenUtil.instance =
        ScreenUtil(width: 750, height: 1304, allowFontScaling: true)
          ..init(context);
    return new FutureBuilder(
        future: DefaultAssetBundle.of(context)
            .loadString('assets/json/register/2.1Register.json'),
        builder: (context, snapshot) {
          //  Autogenerated users;
          var parsedJson;
          if (snapshot.hasData) {
            parsedJson = json.decode(snapshot.data.toString());
            //  users = Autogenerated.fromJson(parsedJson);
            return new Scaffold(
              //   drawer: DrawerMenu().getDrawer,
              appBar: AppBar(
                leading: Builder(
                  builder: (BuildContext context) {
                    return IconButton(
                      icon: const Icon(Icons.arrow_back_ios),
                      onPressed: () {
                        Navigator.pop(context);
                      },
                    );
                  },
                ),
                centerTitle: true,
                title: Text(
                    translator.translate("register").toString().toUpperCase()),
                flexibleSpace: Image(
                  image: AssetImage('assets/appbar_bg.png'),
                  height: 100,
                  fit: BoxFit.fitWidth,
                ),
                actions: <Widget>[
                  IconButton(
                    padding: const EdgeInsets.only(right: 20.0),
                    icon: Icon(
                      Icons.chat_bubble_outline,
                      color: Colors.white,
                    ),
                    onPressed: () {
                      // do something
                    },
                  )
                ],
              ),
              body: SingleChildScrollView(
                  child: Padding(
                      padding: EdgeInsets.only(left: 30.0, right: 30.0),
                      child: Column(
                        children: <Widget>[
                          SizedBox(
                            height: ScreenUtil.getInstance().setWidth(60),
                          ),
                          Align(
                            alignment: Alignment.centerLeft,
                            child: Text(
                              translator.translate("createWallet"),
                              style: TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                                color: Colors.black,
                              ),
                            ),
                          ),
                          SizedBox(
                            height: ScreenUtil.getInstance().setWidth(50),
                          ),
                          Container(
                            child: Text(
                              translator.translate("signup"),
                              style: TextStyle(
                                fontSize: 16,
                                color: Colors.black45,
                              ),
                            ),
                            width: ScreenUtil.getInstance().setWidth(690),
                          ),
                          SizedBox(
                            height: ScreenUtil.getInstance().setHeight(200),
                          ),
                          Align(
                            alignment: Alignment.topLeft,
                            child: Text(
                              translator
                                  .translate("phoneNo")
                                  .toString()
                                  .toUpperCase(),
                              style: TextStyle(
                                fontSize: 12,
                                color: Colors.black45,
                              ),
                            ),
                          ),
                          SizedBox(
                            height: ScreenUtil.getInstance().setHeight(20),
                          ),
                          Container(
                            child: Padding(
                              padding: EdgeInsets.only(left: 10.0, right: 10.0),
                              child: _checkPhone
                                  ? Container(
                                      child: Text(
                                        '',
                                        style: TextStyle(
                                          color: Colors.black38,
                                        ),
                                      ),
                                      height: 0,
                                    )
                                  : Row(
                                      children: <Widget>[
                                        Text(
                                          translator
                                              .translate("userhavealready"),
                                          style: TextStyle(
                                            color: Colors.red,
                                          ),
                                        ),
                                        GestureDetector(
                                          onTap: () {
                                            Navigator.pop(context);
                                          },
                                          child: Text(
                                            translator.translate("login"),
                                            style: TextStyle(
                                              color: Colors.blue,
                                            ),
                                          ),
                                        )
                                      ],
                                    ),
                            ),
                          ),
                          TextField(
                            onChanged: (text) {
                              if (text.length > 0 && !_checkPhone) {
                                setState(() {
                                  _checkPhone = true;
                                });
                              }
                            },
                            style: TextStyle(
                                color: _checkPhone ? Colors.black : Colors.red),
                            controller: _phoneController,
                            keyboardType: TextInputType.phone,
                            decoration: InputDecoration(
                              hintText: translator.translate("PhoneNo"),
                              hintStyle: CustomTextStyle.formField(context),
                              enabledBorder: UnderlineInputBorder(
                                  borderSide: BorderSide(
                                      color: _checkPhone
                                          ? Colors.black38
                                          : Colors.red,
                                      width: 1.0)),
                              focusedBorder: UnderlineInputBorder(
                                  borderSide: BorderSide(
                                      color: _checkPhone
                                          ? Colors.black38
                                          : Colors.red,
                                      width: 1.0)),
                              prefixIcon: _checkPhone
                                  ? const Icon(
                                      Icons.phone,
                                      color: Colors.black38,
                                    )
                                  : const Icon(
                                      Icons.cancel,
                                      color: Colors.red,
                                    ),
                            ),
                            inputFormatters: [
                              WhitelistingTextInputFormatter.digitsOnly,
                              // Fit the validating format.
//                _phoneNumberFormatter,
                            ],
                            obscureText: false,
                          ),
                          SizedBox(
                            height: ScreenUtil.getInstance().setHeight(30),
                          ),
                          Align(
                            alignment: Alignment.centerRight,
                            child: FlatButton(
                              onPressed: () {
                                Navigator.pop(context);
                              },
                              child: Text(
                                translator.translate("have"),
                                style: TextStyle(
                                  color: Colors.blue,
                                  fontSize: 16,
                                ),
                              ),
                            ),
                          ),
                          SizedBox(
                            height: ScreenUtil.getInstance().setHeight(60),
                          ),
                          Container(
                            child: FlatButton(
                              onPressed: () {
                                if (_phoneController.text.length == 0) {
                                  Navigator.pushNamed(context, '/registration');
                                } else {
                                  setState(() {
                                    _checkPhone = false;
                                  });
                                }
                              },
                              color: Colors.blue,
                              disabledColor: Colors.blue,
                              padding: EdgeInsets.all(15.0),
                              child: Text(
                                translator
                                    .translate("register")
                                    .toString()
                                    .toUpperCase(),
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 16,
                                ),
                              ),
                            ),
                            width: ScreenUtil.getInstance().setWidth(690),
                          ),
                          SizedBox(
                            height: ScreenUtil.getInstance().setHeight(250),
                          ),
                          Container(
                            child: RichText(
                                text: TextSpan(
                                    // set the default style for the children TextSpans
                                    style: TextStyle(
                                      fontSize: 16,
                                    ),
                                    children: [
                                  TextSpan(
                                      text: translator.translate("Userprivacy"),
                                      style: TextStyle(color: Colors.blue)),
                                  TextSpan(
                                      text: " " +
                                          translator.translate("and") +
                                          " ",
                                      style: TextStyle(color: Colors.black45)),
                                  TextSpan(
                                      text: translator.translate("PPplicy"),
                                      style: TextStyle(color: Colors.blue)),
                                ])),
                          )
                        ],
                      ))),
            );
          } else if (snapshot.hasError) {
            return Text("${snapshot.error}");
          }
          return CircularProgressIndicator();
        });
  }
}

class Autogenerated {
  String header;
  String create;
  String sign;
  String phone;
  String have;
  String button;
  User user;
  Fail fail;

  Autogenerated(
      {this.header,
      this.create,
      this.sign,
      this.phone,
      this.have,
      this.button,
      this.user,
      this.fail});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    header = json['header'];
    create = json['create'];
    sign = json['sign'];
    phone = json['phone'];
    have = json['Have'];
    button = json['button'];
    user = json['User'] != null ? new User.fromJson(json['User']) : null;
    fail = json['fail'] != null ? new Fail.fromJson(json['fail']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['header'] = this.header;
    data['create'] = this.create;
    data['sign'] = this.sign;
    data['phone'] = this.phone;
    data['Have'] = this.have;
    data['button'] = this.button;
    if (this.user != null) {
      data['User'] = this.user.toJson();
    }
    if (this.fail != null) {
      data['fail'] = this.fail.toJson();
    }
    return data;
  }
}

class User {
  String user;
  String and;
  String privacy;

  User({this.user, this.and, this.privacy});

  User.fromJson(Map<String, dynamic> json) {
    user = json['User'];
    and = json['and'];
    privacy = json['privacy'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['User'] = this.user;
    data['and'] = this.and;
    data['privacy'] = this.privacy;
    return data;
  }
}

class Fail {
  String user;
  String login;

  Fail({this.user, this.login});

  Fail.fromJson(Map<String, dynamic> json) {
    user = json['user'];
    login = json['login'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['user'] = this.user;
    data['login'] = this.login;
    return data;
  }
}
