name: fluttersipay
description: A new Flutter application.
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+11
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  flutter_screenutil:
  flutter_swiper:
  background_app_bar:
  image_picker:
  provider:
  flutter_spinkit:
#  flushbar:
#    git:
#      url: git://github.com/valterh4ck3r/flushbar
  http:
  dart_math:
  font_awesome_flutter:
  mask_text_input_formatter:
  country_pickers:
  shared_preferences:
  quiver: any
  percent_indicator:
  intl:
  flutter_datetime_picker:
  gradient_text:
  sphere_bottom_navigation_bar:
  country_icons:
  date_field:
  flutter_html:
  simple_timer:
  translator:
  country_provider: any
  dio: any
  ola_like_country_picker:
  easy_dialog: any
  websafe_svg:
  animated_dialog:
  month_picker_dialog:
  localize_and_translate:
  flutter_share_me:
  uni_links:
  flutter_webview_plugin:
  local_auth:
  get_it:
  device_info:
  signature:
  cached_network_image:
dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/appbar_bg.png
    - assets/user_avatar_two.png
    - assets/card.png
    - assets/mobile/
    - assets/splash/
    - assets/deposit.png
    - assets/down_time.png
    - assets/home_logo.png
    - assets/sipay_splash.png
    - assets/json/deposit/6.1DepositMethod.json
    - assets/json/deposit/6.2.1Deposit_succes.json
    - assets/json/deposit/6.2Deposit_Transfer.json
    - assets/json/deposit/6.3Deposit_card.json
    - assets/json/register/2.1Register.json
    - assets/json/register/2.2Registration.json
    - assets/json/register/2.3registerSMSverification1.json
    - assets/json/register/2.3registerSMSverification2.json
    - assets/json/register/2_4KYC.json
    - assets/json/Withdrawl/8.5Withdraw.json
    - assets/json/Withdrawl/8.6Withdraw_request.json
    - assets/json/Withdrawl/8.7Withdraw_success.json
    - assets/json/dashboard/c_merchant_panel.json
    - assets/json/dashboard/merchant_panel.json
    - assets/json/dashboard/add_new_account.json
    - assets/json/dashboard/edit_bank_accounts.json
    - assets/json/dashboard/footer_tab.json
    - assets/logo-dashboard.png
    - assets/slide.png
    - assets/user_avatar.png
    - assets/withdraw.png
    - assets/dash_back.png
    - assets/welcome.png
    - assets/money_transfer.png
    - assets/password.png
    - assets/verify_attention.png
    - assets/confirm.png
    - assets/langs/en.json
    - assets/job.png
    - assets/langs/tr.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages