/// Generated by AssetsRefGenerator on 2020/03/05
class Res {
  static const String appbar_bg = "assets/appbar_bg.png";
  static const String home_logo = "assets/home_logo.png";
  static const String slide = "assets/slide.png";
}
